version: '3'

services:
  django:
    container_name: ticaret
    build:
        context: .
    image: ticaret
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: python manage.py runserver 0:8000
    tty: true