# Generated by Django 4.0.5 on 2022-06-06 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.CharField(choices=[('red', 'Red'), ('yellow', 'Yellow'), ('blue', 'Blue'), ('purple', 'Purple'), ('green', 'Green'), ('pink', 'Pink')], max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(choices=[('X Small', 'Xs'), ('Small', 'S'), ('Medium', 'M'), ('Large', 'L'), ('X Large', 'Xl'), ('XX Large', 'Xxl')], max_length=255),
        ),
    ]
