# Generated by Django 4.0.5 on 2022-06-06 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_productcategory_options_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.TextField(max_length=255, null=True),
        ),
    ]
