# Generated by Django 4.0.5 on 2022-06-06 20:45

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0002_alter_basket_user'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='basket',
            managers=[
                ('manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveField(
            model_name='basket',
            name='transaction_id',
        ),
    ]
