# Generated by Django 4.0.5 on 2022-06-06 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('color', models.CharField(choices=[('X Small', 'Xs'), ('Small', 'S'), ('Medium', 'M'), ('Large', 'L'), ('X Large', 'Xl'), ('XX Large', 'Xxl')], max_length=255)),
                ('stock', models.PositiveIntegerField()),
                ('size', models.CharField(choices=[('red', 'Red'), ('yellow', 'Yellow'), ('blue', 'Blue'), ('purple', 'Purple'), ('green', 'Green'), ('pink', 'Pink')], max_length=255)),
            ],
        ),
    ]
