# Generated by Django 4.0.5 on 2022-06-06 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0003_alter_basket_managers_remove_basket_transaction_id'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='basket',
            managers=[
            ],
        ),
    ]
